name: Android Build

on:
  push:
    tags:
      - 'v*'

env:
  IS_STABLE: ${{ !contains(github.ref, '-') }}

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.35.5
         cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate SDK Code
        run: |
          cd lib/sdk/flutter_xboard_sdk
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          cd ../../..

      - name: Generate Main Project Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        run: flutter build apk --release

      - name: Prepare dist folder
        run: |
          mkdir dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/

      - name: Generate sha256
        run: |
          cd dist
          for file in *; do
            sha256sum "$file" > "$file.sha256"
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: dist/*

      - name: Create Release
        if: ${{ env.IS_STABLE == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
